import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";
import theme from "../theme";
import localFont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const sf = localFont({
//   src: [
//     {
//       path: "/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYBOLD.OTF",
//       weight: "700",
//       style: "normal",
//     },
//     {
//       path: "/fonts/sf-pro-display-cufonfonts/SFPRODISPLAYMEDIUM.OTF",
//       weight: "500",
//       style: "normal",
//     },
//   ],
//   variable: "--font-sf",
// });

// const sp = localFont({
//   src: [
//     {
//       path: "/fonts/sofia-pro/Sofia Pro Bold Az.otf",
//       weight: "700",
//       style: "normal",
//     },
//   ],
//   variable: "--font-sp",
// });

// className={` ${sf.variable} ${sp.variable} `}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider theme={theme}>{children}</ChakraProvider>
      </body>
    </html>
  );
}
