import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ChakraProvider } from "@chakra-ui/react";

import theme from "../theme";
import localFont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });
// import z from "../fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sf = localFont({
  src: [
    {
      path: "../fonts/sf-pro/SFPRODISPLAYBOLD.OTF",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/sf-pro/SFPRODISPLAYMEDIUM.OTF",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/sf-pro/SFPRODISPLAYREGULAR.OTF",
      weight: "500",
      style: "normal",
    },
  ],
});

const sp = localFont({
  src: [
    {
      path: "../fonts/sofia-pro/sofia_pro_bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sp.className}`}>
        <ChakraProvider theme={theme}>{children}</ChakraProvider>
      </body>
    </html>
  );
}
